### ISSUE TITLE
Auto-memoization support for \citefield (Biblatex)

### ISSUE THREAD

**Issue by cfr42** [sasozivanovic/memoize#12]
Thank you very much for adding basic support for memoizing code involving Biblatex macros: `\cite` and `\cites`!

### Feature requests: 

1. Document this with example showing how to enable auto-memoization of other citation commands.
1. Either add support for Biblatex's `\citefield` or explain how to handle this case in the documentation. 

### Document current support:

It is trivial to extend the support for `\cite`/`\cites` to a broader range of citation macros. For example, `\autocite` can be supported simply with

``` latex
      auto=\autocite{cite},
```

 But the task is trivial only if you read the package code to see how `\cite` and `\cites` are setup (and even _that_ they're setup). Personally, I never use `\cite` or `\cites`, so I'd never realise the support existed if you'd not told me it was coming.

### `\citefield` et al.

It is less straightforward to add support for `\citefield` and friends. I asked [this question on TeX SE](https://tex.stackexchange.com/q/707771/), but either nobody else is interested or no one has any bright ideas. But I use `\citefield` or `\citename` relatively often, so this is not simply a hypothetical request. 

Currently I have a partially working solution involving a `cite field` style which calls a custom `outer handler`.

 ``` latex
       auto/cite field/.style={run if memoizing, args=oomom, outer handler=\mmz@auto@citefield},
```

where `outer handler` is defined as

``` latex
    \NewDocumentCommand \mmz@auto@citefield { O{} O{} m O{} m}
    {% purloined from memoize.sty & mangled
      \xtoksapp\mmzCCMemo{%
        \noexpand\nocite{#3}%
      }%
      \AdviceOriginal[#1][#2]{#3}[#4]{#5}%  
    }
```

Then I can use, for example,

``` latex
      auto csname={citefield}{cite field},
      auto csname={citelist}{cite field},
      auto csname={citename}{cite field},
```

However, the context-sensitivity doesn't work correctly so I need

``` latex
       auto csname={abx@missing}{abort},
```
and nothing is auto-regenerated if, say, the output of the citation command changes. 

MWE:

``` latex
    \documentclass{article}
    
    \usepackage{memoize}
    \usepackage{biblatex}
    \bibliography{biblatex-examples}
    \usepackage{tikz}
    \makeatletter
    \mmzset{%
      prefix=memos/,
      begindocument/before/.append style={%
        auto=\autocite{cite},
        auto csname={abx@missing}{abort},
        auto/cite field/.style={run if memoizing, args=oomom, outer handler=\mmz@auto@citefield},
        auto csname={citefield}{cite field},
        auto csname={citelist}{cite field},
        auto csname={citename}{cite field},
      },
    }
    \NewDocumentCommand \mmz@auto@citefield { O{} O{} m O{} m}
    {% purloined from memoize.sty & mangled
      \xtoksapp\mmzCCMemo{%
        \noexpand\nocite{#3}%
      }%
      \AdviceOriginal[#1][#2]{#3}[#4]{#5}%  
    }
    \makeatother
    
    \begin{document}
    \begin{tikzpicture}
    	\node [draw] {\autocite{westfahl:space}};
    \end{tikzpicture}
    \begin{tikzpicture}
    	\node [draw] {\citefield{westfahl:space}{booktitle}};
    \end{tikzpicture}
    \begin{tikzpicture}
    	\node [draw] {\citename{westfahl:space}{author}};
    \end{tikzpicture}
    \begin{tikzpicture}
    	\node [draw] {\citelist{westfahl:space}{location}};
    \end{tikzpicture}
    \printbibliography
    \end{document}
```

**Comment by sasozivanovic** [comment]
Your `cite field` was missing a crucial component: a call to the internal `\mmz@biblatex@cite@do@key`, which adds the key to the context and aborts if it is not defined.

In 9c0dbed, I have changed the definition of `cite` so that it is now applicable to `\citefield` etc. as well. Surprisingly enough, this required a very small change. Instead of putting the original command into the cc-memo (`\mmzCCMemo`), I take a leaf out of your book and issue a `\nocite`. The outer handler only grabs the arguments up to and including the `{<key>}` argument, but the `{<key>}` is now all it needs to do the job, so any arguments (like the cite field) may follow.

Bottom-line, one can now simply say `auto=\citefield{cite}` — with one caveat: this has to be done in the document body (or inside `\AddToHook{begindocument}`), as Memoize only loads Biblatex support in hook `begindocument/before`. I'm not happy with this, of course, and I'm trying to find a way to make it better. Ideas are welcome.

Incidentally, `args=oomom` in the definition of `cite field` above is superfluous. Outer handlers do not use this option — note that `\mmz@auto@citefield` was as defined `O{} O{} m O{} m` anyway.

Please test.

**Comment by sasozivanovic** [comment]
The docs are coming up next ;-)

**Comment by cfr42** [comment]
I'm not sure I follow that, but it now seems to work with minimal testing. Thanks!

**Comment by cfr42** [comment]
Could you figure out a way to give a more helpful error if the configuration is done too early? Right now the error is really misleading. But I don't know if this is the bit you're asking for suggestions about or if you are asking for suggestions about ways not to have to do the configuration later. 

I also don't know if this would be easy or hard, but there's no straightforward way to tell Memoize not to touch Biblatex. That's less than ideal in cases like this where a bug essentially renders the package unloadable in any document which loads Biblatex. It might be best if the code was only used if the user opts in, since lots of people probably use Biblatex without needing it in anything they want to externalize. Not having externalisation was a pain for me, so it's one of the first things I looked for in Memoize, but I suspect lots of people never use citation commands in diagrams.

**Comment by sasozivanovic** [comment]
Thanks for your thoughts, I agree selective support for Biblatex, and probably other packages as well, would be a good thing. I like how your final piece of code solves both selective support and the timing problems at once.

**Comment by sasozivanovic** [comment]
`\citefield` etc, `\volcites` etc. are all supported now. As suggested, `biblatex` support is loaded via ` \mmzset{biblatex}`. The customization argument to this key is supported, although it won't be used much, I guess, as all citation commands are submitted to `auto` out of the box.

**Comment by cfr42** [comment]
I have custom citation commands. I don't know how common that is, but I definitely appreciate a way to submit those to `auto`.
