### ISSUE TITLE
Error if cited bib entry includes verbatim field (e.g. url or file) even if nothing is memoized

### ISSUE THREAD

**Issue by cfr42** [sasozivanovic/memoize#13]
Minimal Non-Working Example:

```latex
\documentclass{article}
\usepackage{memoize}
\mmzset{prefix=memos/}
\usepackage{biblatex}
\bibliography{biblatex-examples}
\begin{document}
  \cite{padhye}
\end{document}
```

Compilation sequence:

```bash
TEXMFHOME=/d pdflatex <filename>
TEXMFHOME=/d biber <filename>
TEXMFHOME=/d pdflatex <filename>
```

Compilation fails with the error

```latex
! Use of \blx@bbl@verbadd@i doesn't match its definition.
<argument> ...d {dateera}{ce} \verb {file} \verb f
                                                  tp://gaia.cs.umass.edu/pub...
l.69     \endentry
                  
? 
```

Similarly,

```latex
\documentclass{article}
\usepackage{memoize}
\mmzset{prefix=memos/}
\usepackage{biblatex}
\bibliography{biblatex-examples}
\begin{document}
  \cite{markey}
\end{document}
```
yields
```latex
! Use of \blx@bbl@verbadd@i doesn't match its definition.
<argument> ...ldateera}{ce} \verb {urlraw} \verb h
                                                  ttp://mirror.ctan.org/info...
l.60     \endentry
                  
? 
```
I'm assuming any field requiring verbatim handling will produce a similar error.

[I'm really sorry; you must be cursing me for ever mentioning Biblatex.]

**Comment by cfr42** [comment]
Very minimal testing suggests this now works - and so does automemoising `\citelist`, `\citefield` et al. Thanks!

Off-topic: I can't compile everything from your source, but I'm not sure this isn't due to my unfamiliarity with git, make etc. It looks like trying to compile the documentation fails. If you want me to file a bug, let me know.

**Comment by sasozivanovic** [comment]
Happy it works! Incidentally, I realized there's also `\volcite` and friends. For the sake of completeness, I'll make those work as well.

Yeah, compiling the docs has a couple of issues, I'll work on that at some point, no need to file a bug report.

**Comment by cfr42** [comment]
> @sasozivanovic Only discovered today that this is the issue caussing me problems while trying to switch from tikzexternalize. Is there a plan to make a release with this fix? Or should I think about installing a local version.

@Laar  This is in both the current release and the previous one. Which version of `memoize` do you have? The current version is 1.3.0, but 1.2.0 should also work. If you have the current version, can you provide a minimal example reproducing the error with the `.log`, `.tex` and `.bib`?

**Comment by cfr42** [comment]
@Laar  You might want to open a new issue, though, since this one is closed.

**Comment by sasozivanovic** [comment]
> @sasozivanovic Only discovered today that this is the issue caussing me problems while trying to switch from tikzexternalize. Is there a plan to make a release with this fix? Or should I think about installing a local version.

Sure I plan to release it, I just haven't found the time to finalize the release yet. Not much remains for me to do, but I'm afraid I'm swamped with other stuff ... 

So in short, yes please try installing the github version: release Memoize 1.4.0-wip, the TDS inside the [zip](https://github.com/sasozivanovic/memoize/releases/download/memoize-1.4.0-wip/memoize-2024-10-21-v1.4.0-wip.zip).

**Comment by Laar** [comment]
It seems that I understood the output of the local tooling wrong, suggesting that I had version 1.3 while actually having 1.1.3. After installing it locally from CTAN it now all works :). So sorry to bother you with the issue.

**Comment by sasozivanovic** [comment]
No problem at all, glad it worked out well.
