### ISSUE TITLE
CHANGELOG.md missing changes for version 1.2

### ISSUE THREAD

**Issue by cfr42** [sasozivanovic/memoize#14]
Thanks for adding information about where to find a list of changes to the manual. Unfortunately, the file referenced seems not to cover the changes in version 1.2 now on CTAN. Maybe this got overlooked?

**Comment by sasozivanovic** [comment]
Weird, I cannot reproduce this. The link takes *me* to the newest version, 1.2.0.  Maybe something with your browser cache? Or a CTAN mirror which wasn't (yet) updated?

**Comment by cfr42** [comment]
Very sorry. This is my fault. Apologies for the noise.

**Comment by sasozivanovic** [comment]
No problem!
