### ISSUE TITLE
Handling of & in memoized code

### ISSUE THREAD

**Issue by cfr42** [sasozivanovic/memoize#17]
This may be a documentation request because it isn't clear to me that `memoize` could avoid errors here. But it would be good if memoize could either identify the problem (preferably) or include an explanation in the manual. If the issue is documented and I didn't find it, indexing `&`, `ampersand` and/or the error and/or the most common environment/package triggers would be helpful.

MNWE

```latex
\documentclass{article}
\usepackage{memoize}
\usepackage{tikz}
\usetikzlibrary{matrix}
\begin{document}
\begin{tikzpicture}
  \matrix (m) [matrix of nodes]
  {
    a & b & c\\
    d & e & f\\
  };
\end{tikzpicture}
\end{document}
```
This fails as follows
```latex
(./prawf.944AD362A4B16C60FEC388997EA807BE.memo)
! Undefined control sequence.
<argument> \pgf@matrix@last@nextcell@options

l.893 \end{tikzpicture}

?
! Undefined control sequence.
<argument> \pgf@matrix@last@nextcell@options

l.893 \end{tikzpicture}

?
Missing character: There is no b in font nullfont!

! Package pgf Error: Single ampersand used with wrong catcode.

See the pgf package documentation for explanation.
Type  H <return>  for immediate help.
...

l.893 \end{tikzpicture}

?
```
Only the last error gives any clear indication of what's wrong. Since most editors will stop at the first error, many users won't get that hint.

It would be helpful to document the(?) solution.
```latex
\begin{tikzpicture}[ampersand replacement=\&]
  \matrix (m) [matrix of nodes]
  {
    a \& b \& c\\
    d \& e \& f\\
  };
\end{tikzpicture}
```

Perhaps also worth noting that `forest` doesn't require this.
```latex
\documentclass{article}
\usepackage{memoize}
\usepackage{forest}
\begin{document}
\begin{forest}
  for tree={align=cc},
  [a
    [b & c]
  ]
\end{forest}
\end{document}
```
This case works as-is, presumably because `forest` handles the catcodes or `memoize` includes special handling.

Note that I've still got version 1.2, but I looked through the change log and searched the new documentation for `ampersand` and didn't see any relevant changes. I've also read most of the issues on github and don't remember this coming up.

**Comment by sasozivanovic** [comment]
Indeed, I cannot address this other than in the documentation.

The issue is not the ampersand per se. Any environment which changes the category code of some character (TikZ matrices change the catcode of `&` to 13, active) will run into the same problem, and receive — from Memoize — the same solution: `verbatim`. (Incidentally, your Forest example does not present a problem because Forest's `align` uses the standard `tabular` environment, which does not change the catcode of `&`.)

As far as I see, the best I can do is to emphasize the category codes in the `verbatim` section of the tuturial (2.9).  As it stands, the section might give the impression that key `verbatim` is only useful for verbatim environments, whereas in fact it presents the solution to all catcode problems. I actually like the matrix example a lot; I think I want to include it in this section. This section might also be the best place for the suggested list of the most common environments exhibiting the problem.

I will also add the index entry, as suggested — something like "category codes, problems with" — and a paragraph to the troubleshooting section (6.3).

**Comment by cfr42** [comment]
Thanks. I figured it was most likely a doc request.

Do I understand correctly that the problem arises from the fact that an environment makes the character active? So if `&` was active throughout the document, it wouldn't be a problem? To be clear: I do realise this would cause _other_ problems. I'm not asking if this would 'solve' anything; I'm just trying to understand what happens. 

memoize doesn't seem to care whether I use `verbatim` or not for characters I've made active generally. 

I suspect people are unlikely to find the index entry if they don't see the second part of the error message, which they won't if their editor just halts immediately on error. So I do think including some common examples of troublesome environments in the troubleshooting would be really helpful. Even if people run into the problem for a different environment, at least some of them will pick up the similarity. 

>  (Incidentally, your Forest example does not present a problem because Forest's align uses the standard tabular environment, which does not change the catcode of &.)

Sorry. I should disappear.

**Comment by sasozivanovic** [comment]
> Do I understand correctly that the problem arises from the fact that an environment makes the character active? So if `&` was active throughout the document, it wouldn't be a problem? 

Yes, I believe this is the case.

> I suspect people are unlikely to find the index entry if they don't see the second part of the error message, which they won't if their editor just halts immediately on error. 

I am being too nasty if I suggest they get another editor then? ;-)

I mean, in the (La)TeX world, error messages are cryptic enough as it is, and often enough, the first error message is not the most informative ...

> So I do think including some common examples of troublesome environments in the troubleshooting would be really helpful. Even if people run into the problem for a different environment, at least some of them will pick up the similarity.

I completely agree!

> > (Incidentally, your Forest example does not present a problem because Forest's align uses the standard tabular environment, which does not change the catcode of &.)
> 
> Sorry. I should disappear.

This, I absolutely forbid!

**Comment by sasozivanovic** [comment]
Btw, as you can see in issue #19, I'm now considering a major revision of the verbatim section of the tutorial.

**Comment by cfr42** [comment]
> > I suspect people are unlikely to find the index entry if they don't see the second part of the error message, which they won't if their editor just halts immediately on error.
> 
> I am being too nasty if I suggest they get another editor then? ;-)
> 
> I mean, in the (La)TeX world, error messages are cryptic enough as it is, and often enough, the first error message is not the most informative ...

I'm ashamed to admit that every editor I've tried or used has done this except for Overleaf. (Actually my editor has recently gone somewhat mad, so hiding compilation errors is not high on my list of complaints.) 

> > So I do think including some common examples of troublesome environments in the troubleshooting would be really helpful. Even if people run into the problem for a different environment, at least some of them will pick up the similarity.
> 
> I completely agree!
> 
> > > (Incidentally, your Forest example does not present a problem because Forest's align uses the standard tabular environment, which does not change the catcode of &.)
> > 
> > 
> > Sorry. I should disappear.
> 
> This, I absolutely forbid!

**Comment by cfr42** [comment]
> This, I absolutely forbid!

Thank you.

**Comment by sasozivanovic** [comment]
That's good to know, I only ever used Emacs + AUCTeX ... (and Overleaf, occasionally).

**Comment by sasozivanovic** [comment]
I pushed the documentation update of section 2.9 discussed above. See prerelease 1.4.0-wip.

**Comment by sasozivanovic** [comment]
I also created a [Wiki page](https://github.com/sasozivanovic/memoize/wiki), here at GitHub, which lists the issues caused by various commands (and provides a solution, if possible). The idea is that this list would be a community effort ;-)

**Comment by sasozivanovic** [comment]
(I'm experimenting with the form of the list, let me know what you think.)

**Comment by cfr42** [comment]
I like the structure and I think this could be very useful, but the use of `auto` is a bit confusing. On the one hand, it refers to things you have to do to automatise memoization. On the other, it refers to things you don't have to do to automatise memoization. That makes perfect sense in the docs, but here it seems a bit odd to list something with label `auto` when that's described as a label for issues concerning automatisation. I think a different label for one or the other would be more useful from a user perspective. Or maybe `auto` versus `auto (config)` or something? So it's clear it is the same process but obvious at a glance whether anything needs to be done to enable that process?

Tikz:matrix -> Tikz as I assume the issue arises whether the library is used or not. Or does `Tikz:matrix` mean something else here?

Hyperlinks would be a useful addition?

I'm not sure about the 'community' bit. There's no obvious way to suggest changes? Or am I supposed to clone it and submit a pull request?

**Comment by cfr42** [comment]
> > I'm not sure about the 'community' bit. There's no obvious way to suggest changes? Or am I supposed to clone it and submit a pull request? I worry this will be just another thing you have to do.
> 
> Hmm. Could you perhaps test whether the pull request is the way to go? (If you agree with "auto" –> "argument structure", you could try changing that.) I can't test this myself, I've got an "Edit" button ;-)

Sorry, this is beyond my current`git` skills. I have been trying to learn it, but I am absolutely not reliable for current purposes<sup>1</sup>. I can clone it locally and edit, but I have no idea what to do next. I have a fork of `memoize`, but if I try to do something there I'm just starting from a blank page. It doesn't behave like part of your `memoize` repo and it doesn't behave like an independent repo in its own right. 

If you can tell me what I'm meant to do, I'll happily try to do it, but I'm lost.

<sub><sup>1</sup>https://chat.stackexchange.com/transcript/message/66454186#66454186 | https://chat.stackexchange.com/transcript/message/66458579#66458579 | https://chat.stackexchange.com/transcript/message/66463044#66463044</sub>

**Comment by cfr42** [comment]
https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages:

> Wikis are part of Git repositories, so you can make changes locally and push them to your repository using a Git workflow.

But a fork of the repository doesn't include it ....

> Once you have cloned the wiki, you can add new files, edit existing ones, and commit your changes. You and your collaborators can create branches when working on wikis, but only changes pushed to the default branch will be made live and available to your readers.

But only collaborators? There doesn't seem to be anything about contributions from non-collaborators?

**Comment by sasozivanovic** [comment]
I have now unticked `Restrict editing to collaborators only`, let's see how much damage results from that ;-)

**Comment by cfr42** [comment]
> The idea was that the issue pertains to library `matrix` of package `tikz`. I don't think you can even use command `\matrix` without loading this library.

Page 709 PGF manual:

> This library package defines additional styles and options for creating matrices. The basic matrix styles
> and options can be found in Section 20.

Page 319 for the basic stuff, including `\matrix`.

**Comment by sasozivanovic** [comment]
Upst, I should've read the manual! ;-)
Thanks!

**Comment by atticus-sullivan** [comment]
> I have now unticked `Restrict editing to collaborators only`, let's see how much damage results from that ;-)

I thought I've worked worked with github wikis, but apparently I remembered wrong and it was just a plain github.io page (https://xournalpp.github.io/). Maybe this would be also a possibility, moving the wiki to *xyz.github.io* (either based on this repo, or create a completely new one) where users can simply do changes via PRs (which can then be reviewed).

(PS: Don't wonder about the change in the wiki, I just wanted to test how/if you can indeed make changes)

**Comment by sasozivanovic** [comment]
Thanks for the info on `github.io`, I never knew about this, and thanks for the test!

I'll leave the Wiki as it is for now, in the hope that the wiki interface will suffice. I can always switch to `github.io` if it turns out it doesn't.

**Comment by atticus-sullivan** [comment]
Yea github.io is pretty cool. Also in the most simple form you can just use the default jekyl setup (github does this by default) to serve simple markdown files.

But yes, the wiki probably suffices for now.
