### ISSUE TITLE
CTAN?

### ISSUE THREAD

**Issue by JasonGross** [sasozivanovic/memoize#2]
It seems this package is not available on CTAN.  It looks nice (I haven't tried it yet, only discovered it today from https://github.com/pgf-tikz/pgf/issues/758#issuecomment-1480465533), but it seems like it would be nice to have on CTAN

**Comment by test-erik** [comment]
Even better: it will be included in TeXlive and Debian, if you upload it to CTAN.

**Comment by mbertucci47** [comment]
I think this can be closed: https://www.ctan.org/ctan-ann/id/mailman.3286.1697117567.3764.ctan-ann@ctan.org

**Comment by sasozivanovic** [comment]
> I think this can be closed: https://www.ctan.org/ctan-ann/id/mailman.3286.1697117567.3764.ctan-ann@ctan.org

Finally, no? ;-)
