### ISSUE TITLE
\GetDocumentCommandArgSpec used in advice.sty will be removed from kernel

### ISSUE THREAD

**Issue by mbertucci47** [sasozivanovic/memoize#3]
The commands `\(Get|Show)Document(Command|Environment)ArgSpec` and `\ArgumentSpecification` will be removed from the kernel in the next release, available only if `xparse` is explicitly loaded. Details in [this commit](https://github.com/latex3/latex2e/commit/0760f7ceb7d50ed8ee717f4f1f70484f28ff6e4e). The commands `\GetDocumentArgSpec` and `\ArgumentSpecification` are used in the definition of `\advice@CollectArgumentsRaw` so I suppose a change should be made before the next LaTeX release.

**Comment by sasozivanovic** [comment]
I see. That's too bad, Advice (and through it, Memoize) provided a courtesy to the user by retrieving the argument specification through `\GetDocumentArgSpec` on its own.

I assume that the decision to make the change is irreversible? Is there a suggestion on how to deal with the situation properly? Would requiring `xparse` be frowned upon?

**Comment by mbertucci47** [comment]
I asked in the [tex.stackexchange chat](https://chat.stackexchange.com/transcript/message/64587573#64587573). Perhaps someone more knowledgeable than myself has a suggestion

**Comment by sasozivanovic** [comment]
Resolved in 257ba3302cb341e62f39853773cfa21bc8fd4d81.
