### ISSUE TITLE
Documentation shows example with `\mmzset{extract=python}`

### ISSUE THREAD

**Issue by cfr42** [sasozivanovic/memoize#32]
On page 7, the docs include an example using `\mmzset{... extract = python, ...`. (I would copy it, but the docs aren't set up for this so I can't copy it as a block.)

But this doesn't work. I think I even knew this but half-forgot it and went back to the documentation ....

[If you want an example for 'doesn't work', I can provide one, but I don't think this will be a surprise.]

**Comment by sasozivanovic** [comment]
Thanks for the catch!

Fixed. It will appear in the repository once I push my current work.
