### ISSUE TITLE
Defer extraction to `\begin{document}`

### ISSUE THREAD

**Issue by amonakov** [sasozivanovic/memoize#6]
To use Memoize together with [mylatexformat](https://ctan.org/pkg/mylatexformat), I need to pass `extract=no` in the preamble, and explicitly invoke `\mmzset{extract/tex}` in the document.

To provide a minimal example, the preamble in fmt.tex would be:
```latex
\documentclass{article}

\usepackage[trace=true,extract=no]{memoize}
\usepackage{tikz}
```
and the main document would be:
```latex
%&mylatexformat
\csname endofdump\endcsname

\mmzset{extract/tex}

\begin{document}
\begin{tikzpicture}
        \draw (0,0) -- (1,1);
\end{tikzpicture}
\end{document}
```

Would there be any downside in running extractors at `\begin{document}` instead of immediately in the preamble?

**Comment by sasozivanovic** [comment]
I'm afraid there is a downside: some packages, notably TikZ library `fadings`, open the PDF while loaded. Memoize must extract externs before this happens, so doing this at `\begin{document}` is generally too late.

I must admit I never thought of Memoize as a package to be included in a format, simply because it is not a package intended to be present at the production of the final document (mostly because of hyperlinks, even if there are ideas on how to resolve this). But as I see this is a usage case, after all, I can make one thing easier: I can make it so that it is enough to execute a plain `\mmzset{extract}` rather provide an explicit extraction method like `\mmzset{extract/tex}`. Would this be of any help?

**Comment by amonakov** [comment]
> I can make it so that it is enough to execute a plain \mmzset{extract} rather provide an explicit extraction method like \mmzset{extract/tex}. Would this be of any help?

I'm not sure: with `extract=no` in the preamble, extraction method would have to be specified somewhere, right?

Maybe an option to choose between immediate and deferred extraction would help (if that's not too much trouble), but overall I'm happy with the solution shown in the MWE above.

I might have missed it, but I'm not sure that `\usepackage{memoize}` not being pure (in the sense of not just defining macros, but immediately invoking extractors) is documented? Generally it seems ideal if `\usepackage` has no side effects apart from adding definitions.

**Comment by sasozivanovic** [comment]
> I'm not sure: with `extract=no` in the preamble, extraction method would have to be specified somewhere, right?

It would invoke either the package default method (`perl`), or the override from `memoize.cfg`.

> Maybe an option to choose between immediate and deferred extraction would help (if that's not too much trouble), but overall I'm happy with the solution shown in the MWE above.

Given that for the end user, the immediate/deferred extraction option means exactly the same amount of work as your solution above, I would prefer to keep things simple. (Furthermore, the package was designed with the end-of-package extraction point in mind, so I would have to think hard on what kind of trouble changing the extraction point could cause.)

> I might have missed it, but I'm not sure that `\usepackage{memoize}` not being pure (in the sense of not just defining macros, but immediately invoking extractors) is documented? Generally it seems ideal if `\usepackage` has no side effects apart from adding definitions.

This is mentioned (or at least alluded to:) several times, I believe. One is the reference for `extract` in section 5.5. Another is 5.1.

Ok for you to close this one?

**Comment by amonakov** [comment]
Thank you for the explanation, I agree it's better to keep things simple here; closing.
