### ISSUE TITLE
Regression in v1.1.0: externs are not used when `memo dir` is not set

### ISSUE THREAD

**Issue by amonakov** [sasozivanovic/memoize#8]
When `memo dir` is not specified, memoize causes externs to be looked up in the filesystem root `/` instead of current directory `./`. It was working properly in the previous version. As a result, externs are never reused. The other files (`memo` files and makefiles) are still produced and looked up correctly in the current directory.

**Comment by sasozivanovic** [comment]
Thank you for catching this one! (Submitting the patched version to CTAN right away.)
